package course

// publicReturningColumns is the column list for INSERT/UPDATE ... RETURNING on course.courses only
// (no term join). Prefer GetPublicByCourseCode after writes for API responses.
const publicReturningColumns = `
    id,
    course_code,
    title,
    description,
    hero_image_url,
    hero_image_object_position,
    starts_at,
    ends_at,
    visible_from,
    hidden_at,
    schedule_mode,
    relative_end_after,
    relative_hidden_after,
    relative_schedule_anchor_at,
    published,
    markdown_theme_preset,
    markdown_theme_custom,
    grading_scale,
    archived,
    notebook_enabled,
    feed_enabled,
    calendar_enabled,
    question_bank_enabled,
    lockdown_mode_enabled,
    standards_alignment_enabled,
    adaptive_paths_enabled,
    srs_enabled,
    diagnostic_assessments_enabled,
    hint_scaffolding_enabled,
    misconception_detection_enabled,
    course_type,
    created_at,
    updated_at,
    sbg_enabled,
    sbg_proficiency_scale_json,
    sbg_aggregation_rule,
    org_unit_id,
    term_id
`
