output "reserved_ipv4" {
  description = "Reserved (floating) IPv4 attached to the droplet — use this for DNS A records and VITE_API_URL."
  value       = digitalocean_reserved_ip.demo.ip_address
}

output "postgres_volume_id" {
  description = "DigitalOcean block volume ID holding PostgreSQL data (persists across droplet recreation)."
  value       = digitalocean_volume.postgres.id
}

output "postgres_data_mount" {
  description = "Host path used by docker-compose.deploy.yml for Postgres (bind mount from the block volume)."
  value       = "/mnt/lextures-db/postgres"
}

output "course_files_mount" {
  description = "Host path on the droplet for uploaded course files (same DO block volume; bind-mounted into the API container)."
  value       = "/mnt/lextures-db/course-files"
}

output "droplet_ipv4" {
  description = "Ephemeral public IPv4 on the droplet NIC (not stable across recreates; prefer reserved_ipv4 for DNS)."
  value       = digitalocean_droplet.demo.ipv4_address
}

output "ssh_root" {
  description = "Example SSH as root via the reserved IP (works the same as the droplet ephemeral IP)."
  value       = "ssh -i <private-key-file> root@${digitalocean_reserved_ip.demo.ip_address}"
}

output "ssh_private_key_openssh" {
  description = "OpenSSH private key for root (generated by Terraform; use with ssh -i)."
  value       = tls_private_key.demo.private_key_openssh
  sensitive   = true
}

output "ssh_public_key_openssh" {
  description = "OpenSSH public key registered on the droplet (same material as digitalocean_ssh_key)."
  value       = tls_private_key.demo.public_key_openssh
}
