output "droplet_public_ipv4" {
  description = "Public IPv4 address of the demo droplet."
  value       = digitalocean_droplet.demo.ipv4_address
}

output "ssh_root" {
  description = "Example SSH command as root (for debugging)."
  value       = "ssh -i <private-key-file> root@${digitalocean_droplet.demo.ipv4_address}"
}

output "ssh_private_key_openssh" {
  description = "OpenSSH private key for root (generated by Terraform; use with ssh -i)."
  value       = tls_private_key.demo.private_key_openssh
  sensitive   = true
}

output "ssh_public_key_openssh" {
  description = "OpenSSH public key registered on the droplet (same material as digitalocean_ssh_key)."
  value       = tls_private_key.demo.public_key_openssh
}
